# Generated by Django 6.0.6 on 2026-09-05 09:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อหมวดหมู่")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-compass",
                        max_length=50,
                        verbose_name="FontAwesome Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6", max_length=20, verbose_name="สีธีม"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "หมวดหมู่",
                "verbose_name_plural": "หมวดหมู่ทั้งหมด",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="เมือง/จังหวัด")),
                ("zone", models.CharField(max_length=100, verbose_name="ย่าน/ทำเล")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "ทำเล/ย่าน",
                "verbose_name_plural": "ทำเล/ย่านทั้งหมด",
                "ordering": ["city", "zone"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อสถานที่")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="คำบรรยาย / รีวิวสรุป")),
                ("address", models.CharField(max_length=300, verbose_name="ที่อยู่")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL รูปภาพ"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=4.5,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="คะแนนเรตติ้ง (0.0-5.0)",
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="จำนวนรีวิว"),
                ),
                (
                    "price_level",
                    models.IntegerField(
                        choices=[
                            (1, "฿ (ประหยัด)"),
                            (2, "฿฿ (ปานกลาง)"),
                            (3, "฿฿฿ (พรีเมียม)"),
                            (4, "฿฿฿฿ (หรูหรา)"),
                        ],
                        default=2,
                        verbose_name="ระดับราคา",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="คั่นด้วยเครื่องหมายจุลภาค เช่น กาแฟดี, มีที่จอดรถ, วิวหลักล้าน",
                        max_length=255,
                        verbose_name="แท็กคำค้นหา",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="สถานที่แนะนำ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="web.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="web.location",
                        verbose_name="ทำเล/ย่าน",
                    ),
                ),
            ],
            options={
                "verbose_name": "สถานที่",
                "verbose_name_plural": "สถานที่ทั้งหมด",
                "ordering": ["-rating", "-review_count"],
            },
        ),
    ]
