# Generated by Django 6.0.6 on 2026-09-05 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_name",
                    models.CharField(help_text="แท็กชื่อสถานที่ที่ไป", max_length=255),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ที่ตั้ง / จังหวัด / พิกัด",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="สถานที่ท่องเที่ยว",
                        help_text="หมวดหมู่",
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="คะแนนดาวความประทับใจ 1-5 ดาว",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="รีวิวบรรยากาศ ประสบการณ์ และสิ่งที่น่าสนใจ",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, default="", help_text="ลิงก์รูปถ่ายสถานที่"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "travel_posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
