# Generated by Django 6.0.6 on 2026-09-05 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Session Key (สำหรับผู้ใช้ทั่วไป)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่บันทึก"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="web.place",
                        verbose_name="สถานที่",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "สถานที่โปรด (Wishlist)",
                "verbose_name_plural": "รายการสถานที่โปรดทั้งหมด",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "place"),
                        name="unique_user_place_wishlist",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_key__isnull", False)),
                        fields=("session_key", "place"),
                        name="unique_session_place_wishlist",
                    ),
                ],
            },
        ),
    ]
