# Generated by Django 6.1.1 on 2026-09-05 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("like", "กดไลก์ (Like)"),
                            ("review", "เขียนรีวิว (Review)"),
                            ("comment", "แสดงความคิดเห็น (Comment)"),
                            ("follow", "ติดตาม (Follow)"),
                            ("other", "อื่นๆ (Other)"),
                        ],
                        default="like",
                        help_text="ประเภทของแอคชัน เช่น like, review, comment, follow",
                        max_length=50,
                        verbose_name="ทำแอคชันอะไร (Action Type)",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="สถานะกดอ่านแล้วหรือยัง (is_read)",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ข้อความแจ้งเตือน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="เวลาที่เกิดการกระทำ",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="เวลาที่อัปเดตล่าสุด"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ใครเป็นคนกระทำ (Actor / Sender)",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="web.place",
                        verbose_name="กระทำกับโพสต์ไหน (Target Post / Place)",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รับการแจ้งเตือน (Recipient)",
                    ),
                ),
            ],
            options={
                "verbose_name": "การแจ้งเตือน (Notification)",
                "verbose_name_plural": "การแจ้งเตือนทั้งหมด (Notifications)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="web_notific_recipie_f807ad_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="web_notific_created_36f637_idx"
                    ),
                ],
            },
        ),
    ]
