# Generated by Django 6.0.6 on 2026-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelpost",
            name="image_url",
            field=models.TextField(
                blank=True, default="", help_text="รูปถ่ายสถานที่ (URL หรือ Base64 Data URL)"
            ),
        ),
    ]
