# Generated by Django 6.0.6 on 2026-09-05 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
