# Generated by Django 6.0.6 on 2026-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="ละติจูด (Latitude)",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="ลองจิจูด (Longitude)",
            ),
        ),
    ]
