# Generated by Django 6.0.6 on 2026-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="หมวดหมู่"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="ทำเล/ย่าน"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="ที่อยู่"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="คำบรรยาย / รีวิวสรุป"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="image_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL รูปภาพ"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="คั่นด้วยเครื่องหมายจุลภาค เช่น กาแฟดี, มีที่จอดรถ, วิวหลักล้าน",
                max_length=255,
                verbose_name="แท็กคำค้นหา",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
