# Generated by Django 6.0.6 on 2026-09-08 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_place_category_alter_place_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cafe", "คาเฟ่ (Cafe)"),
                    ("restaurant", "ร้านอาหาร (Restaurant)"),
                    ("travel", "สถานที่ท่องเที่ยว (Travel/Attraction)"),
                    ("hotel", "ที่พัก / โรงแรม (Hotel/Resort)"),
                    ("nature", "ธรรมชาติ / แคมป์ปิ้ง (Nature/Camping)"),
                    ("culture", "โบราณสถาน & วัดวาอาราม (Culture/Temple)"),
                    ("other", "อื่นๆ (Other)"),
                ],
                default="travel",
                max_length=100,
                verbose_name="หมวดหมู่",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ใช้",
            ),
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ติดตาม (Follower)",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="กำลังติดตาม (Following)",
                    ),
                ),
            ],
            options={
                "verbose_name": "การติดตามผู้ใช้ (User Follow)",
                "verbose_name_plural": "การติดตามผู้ใช้ทั้งหมด (User Follows)",
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
